#!/usr/bin/env python3
"""
End-to-end validation test: raw trace → semantic graph → validation → success.

This verifies that the validation framework correctly accepts valid semantic
graphs generated by the pipeline.
"""

import json
import subprocess
import sys
from pathlib import Path

import pytest


def test_e2e_valid_trace_passes_validation():
    """Verify that a valid semantic graph from ftrace-semantic passes validation."""
    # Minimal raw trace with a simple linear flow
    raw_trace = {
        "class": "com.example.TestClass",
        "method": "testMethod",
        "blocks": [
            {
                "id": "b1",
                "stmts": [
                    {"line": 10, "chars": "int x = 1"},
                    {"line": 11, "chars": "return x"},
                ],
            }
        ],
        "edges": [],
        "traps": [],
    }

    # Transform to semantic graph
    semantic_graph = transform_to_semantic(raw_trace)

    # Validate: should have no violations
    violations = validate_semantic(semantic_graph)
    assert len(violations) == 0, f"Expected no violations, got {violations}"
    assert semantic_graph["nodes"], "Expected nodes to be generated"
    assert semantic_graph["entryNodeId"], "Expected entry node to be set"


def test_e2e_branch_trace_passes_validation():
    """Verify that a semantic graph with branches passes validation."""
    # Trace with conditional branch
    raw_trace = {
        "class": "com.example.TestClass",
        "method": "testMethod",
        "blocks": [
            {
                "id": "b1",
                "stmts": [
                    {"line": 10, "chars": "int x = 1"},
                    {"line": 11, "chars": "if (x > 0)"},
                ],
                "branchCondition": "x > 0",
            },
            {
                "id": "b2",
                "stmts": [{"line": 12, "chars": "return x"}],
            },
            {
                "id": "b3",
                "stmts": [{"line": 13, "chars": "return -x"}],
            },
        ],
        "edges": [
            {"fromBlock": "b1", "toBlock": "b2", "label": "T"},
            {"fromBlock": "b1", "toBlock": "b3", "label": "F"},
        ],
        "traps": [],
    }

    semantic_graph = transform_to_semantic(raw_trace)
    violations = validate_semantic(semantic_graph)

    assert len(violations) == 0, f"Expected no violations, got {violations}"
    # Branch node should have T and F edges
    branch_edges = [e for e in semantic_graph["edges"] if e.get("branch")]
    assert len(branch_edges) >= 2, "Expected at least 2 branch edges (T and F)"


def test_e2e_pipeline_with_cli():
    """Verify the full pipeline using CLI tools."""
    raw_trace = {
        "class": "com.example.TestClass",
        "method": "testMethod",
        "blocks": [
            {
                "id": "b1",
                "stmts": [{"line": 10, "chars": "test"}],
            }
        ],
        "edges": [],
        "traps": [],
    }

    # Write raw trace to temp file
    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        raw_file = tmpdir / "raw.json"
        semantic_file = tmpdir / "semantic.json"
        validated_file = tmpdir / "validated.json"

        raw_file.write_text(json.dumps(raw_trace, indent=2))

        # Step 1: ftrace-semantic (raw → semantic)
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "ftrace_semantic",
                "--input",
                str(raw_file),
                "--output",
                str(semantic_file),
            ],
            cwd=str(Path(__file__).resolve().parent.parent),
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"ftrace-semantic failed: {result.stderr}"

        # Step 2: ftrace-validate (semantic → validated)
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "ftrace_validate",
                "--input",
                str(semantic_file),
                "--output",
                str(validated_file),
            ],
            cwd=str(Path(__file__).resolve().parent.parent),
            capture_output=True,
            text=True,
        )
        # Should exit 0 for valid graph
        assert (
            result.returncode == 0
        ), f"ftrace-validate failed: {result.stderr} (exit {result.returncode})"

        # Verify output exists
        assert validated_file.exists(), "Validated output file not created"
        validated = json.loads(validated_file.read_text())
        assert validated["class"] == "com.example.TestClass"


def test_ftrace_slice_output_flows_directly_into_ftrace_semantic():
    """Verify ftrace-inter-slice output is directly consumable by ftrace-semantic."""
    xtrace_envelope = {
        "trace": {
            "class": "com.example.Root",
            "method": "entry",
            "methodSignature": "<com.example.Root: void entry()>",
            "lineStart": 10,
            "lineEnd": 20,
            "sourceLineCount": 11,
            "blocks": [
                {
                    "id": "B0",
                    "stmts": [{"line": 11, "call": "com.example.Dao.load"}],
                }
            ],
            "edges": [],
            "traps": [],
            "children": [
                {
                    "class": "com.example.Dao",
                    "method": "load",
                    "methodSignature": "<com.example.Dao: void load()>",
                    "callSiteLine": 11,
                    "ref": True,
                }
            ],
        },
        "refIndex": {
            "<com.example.Dao: void load()>": {
                "class": "com.example.Dao",
                "method": "load",
                "methodSignature": "<com.example.Dao: void load()>",
                "lineStart": 30,
                "lineEnd": 35,
                "sourceLineCount": 6,
                "blocks": [{"id": "B1", "stmts": [{"line": 31}]}],
                "edges": [],
                "traps": [],
                "children": [],
            }
        },
    }

    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        xtrace_file = tmpdir / "xtrace.json"
        slice_file = tmpdir / "slice.json"
        semantic_file = tmpdir / "semantic.json"

        xtrace_file.write_text(json.dumps(xtrace_envelope, indent=2))

        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "ftrace_inter_slice",
                "--input",
                str(xtrace_file),
                "--to",
                "com.example.Dao",
                "--output",
                str(slice_file),
            ],
            cwd=str(Path(__file__).resolve().parent.parent),
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"ftrace-inter-slice failed: {result.stderr}"

        sliced = json.loads(slice_file.read_text())
        assert "trace" in sliced
        assert sliced["trace"]["class"] == "com.example.Root"
        assert "refIndex" in sliced

        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "ftrace_semantic",
                "--input",
                str(slice_file),
                "--output",
                str(semantic_file),
            ],
            cwd=str(Path(__file__).resolve().parent.parent),
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"ftrace-semantic failed: {result.stderr}"

        semantic = json.loads(semantic_file.read_text())
        assert semantic["class"] == "com.example.Root"


# --- Helper functions ---


def transform_to_semantic(raw_trace):
    """Transform raw trace to semantic graph (mimics ftrace-semantic)."""
    # Import locally to avoid circular imports
    from ftrace_semantic import transform

    result, _violations = transform(raw_trace)
    return result


def validate_semantic(semantic_graph):
    """Validate semantic graph (mimics ftrace-validate)."""
    from ftrace_validate import validate_tree

    return validate_tree(semantic_graph)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
